name: remove_emoji
description: Dart package accurately replace/remove emojis in text
version: 0.0.4
homepage: https://github.com/buckthorndev/remove-emoji

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
