name: remove_emoji
description: Dart or flutter package accurately replace/remove emojis in text
version: 0.0.2
homepage: https://github.com/BuckthornInc/remove-emoji

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
